### ISSUE TITLE
to_sql fails silently without a primary key

### ISSUE THREAD

**Issue by mapmeld** [solidsnack/GraphpostgresQL#6]
If a table has no set primary key, to_sql allows queries on the group. When you add an id, to_sql returns an empty string (throwing an exception in graphql.run)

```
osm=# SELECT graphql.to_sql($$
  planet_osm_point {
    name
  }
$$);
-[ RECORD 1 ]----------------------------------------
to_sql | SELECT json_agg("sub/1") AS planet_osm_point
       |   FROM planet_osm_point,
       |        LATERAL (
       |          SELECT planet_osm_point.name
       |        ) AS "sub/1"

osm=# SELECT graphql.to_sql($$
  planet_osm_point("560983277") {
    name
  }
$$);
-[ RECORD 1 ]
to_sql |
```

Ideally to_sql would throw a meaningful error, or return a query based on the "id" column

**Comment by solidsnack** [comment]
I'm not sure how to interpret the spec on this yet -- but it seems like GraphQL is actually moving toward explicit parameters instead of IDs. `planet_osm_point(id: ...)` instead of `planet_osm_point(...)`. For the time being, it can at least raise an error. (Treating the collections as basically all more or less functions would probably be more compatible, incidentally, with the needs of GraphpostgisQL.)

**Comment by mapmeld** [comment]
thanks for fixing this!
